### ISSUE TITLE
tintcolor is missing 

### ISSUE THREAD

**Issue by scorpiozj** [TanguyAladenise/BBBadgeBarButtonItem#13]
Hi, My *UIBarButtonItem* has __tintColor__. And I hope the item can keep it.  
however, it currently doesn't have the tint color.
I tried to add color to the __custom button__ and it failed either.

Please take a look.
![2014-07-16 10 26 45 am](https://cloud.githubusercontent.com/assets/644156/3593960/ada339e8-0c90-11e4-8547-330400c3fc99.png)

**Comment by pot8os** [comment]
Hi, did you try this? I had a same issue but I solved. http://stackoverflow.com/a/21208796

**Comment by scorpiozj** [comment]
The tint color is set like: 

    [[UIBarButtonItem appearance] setTintColor:[UIColor redColor]];

Then the system can render the color itself.  That's what I want.Now I fix it by  re-designing the image for the *UIBarButtonItem*.   
Thanks all the same!
