### ISSUE TITLE
A problem when using BBBadgeBarButtonItem

### ISSUE THREAD

**Issue by mumuyang1** [TanguyAladenise/BBBadgeBarButtonItem#17]
I am Yanzi Li ,a new to learn iOS dev.Sorry to bother you to share my problem when i use BBBadgeBarButtonItem.The problem is that when i set title text for  custom button instead of setting a image for it,the custom button title will cover  a part of badge ,which is not the case i want.I hope the badge will cover a part of the custom button title.  How can i  solve this problem ?Thanks a lot.

**Comment by l900416** [comment]
I think you can try to set  the badge's offseting . hope can be helpful

## like this

   _xxxBarButton.badgeOriginX = 18;

##     _xxxBarButtonBarButton.badgeOriginY = -10;
