### ISSUE TITLE
iOS 9 support

### ISSUE THREAD

**Issue by Ewg777** [TanguyAladenise/BBBadgeBarButtonItem#19]
iOS 9 ignore cornerRadius ![error](http://i.imgur.com/19IAp3w.jpg)

**Comment by jeroentrappers** [comment]
This is due to the animation block. When pulling the code from the animation block, the corners are rounded again, but you lose the animation when the size of the badge is changed.

**Comment by m3ki** [comment]
Do you know of a way to fix this properly while keeping animation?

**Comment by m3ki** [comment]
I was able to fix this issue by changing the this code:
```
    [UIView animateWithDuration:duration animations:^{
        [self updateBadgeFrame];
    }];
```
to
```
[UIView animateWithDuration:duration animations:^{
        [self updateBadgeFrame];
    } completion:^(BOOL finished) {
        self.badge.layer.masksToBounds = YES;
    }];
```

**Comment by Broich** [comment]
Wondering if this project is still alive enough to accept the pull request that fixes this issue.

**Comment by TanguyAladenise** [comment]
Hi guys,

Sorry for not being reactive on the repo. I have a lot on my plate and did not get the chance to work with it and maintain it.
I wanted to take some time to test the fixes and do some refactoring for a new version.
Anyway I will try to do better next time ;)

**Comment by Broich** [comment]
Awesome! Great news, thank you!

**Comment by gabmarfer** [comment]
Please, could you update the pod spec version to match the latest code version?

Thanks in advance!
