### ISSUE TITLE
ios 9 support not fine

### ISSUE THREAD

**Issue by yankunren** [TanguyAladenise/BBBadgeBarButtonItem#22]
ios 9 support not fine

**Comment by madmapper** [comment]
I'll add some real info to this comment - it looks like the corners are not being rounded off on the badge in iOS 9.  Badges appear square.

**Comment by mbelkin** [comment]
Experiencing the same thing here. Strangely when my app launches (with a badge bar button item present), the corners are fine. But when I create a new button in a new view controller, the corners are square.

**Comment by Reedyuk** [comment]
Yes, i can also confirm,when the first badge is created, it is not rounding the corners, but after that it seems to be rounding the corners.

**Comment by yankunren** [comment]
#19
