### ISSUE TITLE
Create release and update podspec

### ISSUE THREAD

**Issue by eightytwo** [TanguyAladenise/BBBadgeBarButtonItem#25]
Hey there,

First of all, thanks for making this UIBarButtonItem badge :)

Last month [a fix for the rounded corners issue on iOS 9](https://github.com/TanguyAladenise/BBBadgeBarButtonItem/commit/28ec386e957b7c0f99825260316b07b78104cb3b) was merged and I was hoping you could make this available via Cocoapods?

Thanks

**Comment by TanguyAladenise** [comment]
Thanks, and yes I know, I have been postponing this for too long. I should
do that today if I can make my build reviewed by Apple. I have been in big
delivery rush. :/

2015-10-13 12:53 GMT+02:00 Piers <notifications@github.com>:

**Comment by eightytwo** [comment]
Not a problem, I'm currently referencing the commit in my Podfile so there's no rush :)
