### ISSUE TITLE
@IBOutlet weak var cartBarItem: BBBadgeBarButtonItem! not working.....

### ISSUE THREAD

**Issue by rosevinod** [TanguyAladenise/BBBadgeBarButtonItem#27]
How to set the bar item for IBoutlet

@IBOutlet weak var cartBarItem: BBBadgeBarButtonItem!
// Add it as the  of the navigation bar
self.cartBarItem = barButtonCart

**Comment by TanguyAladenise** [comment]
Please see issue #7
