### ISSUE TITLE
How must be used directly form storyboard?

### ISSUE THREAD

**Issue by Ricardo1980** [TanguyAladenise/BBBadgeBarButtonItem#7]
If I add a barButtonItem in the navigation bar and change its custom class to BBBadgeBarButtonItem and in my code write:
    BBBadgeBarButtonItem\* chatBarButtonItem=(BBBadgeBarButtonItem*)self.navigationItem.rightBarButtonItem;
    chatBarButtonItem.badgeValue=@"1";
It does not work.
Any help?

**Comment by erf** [comment]
I looked into this now and it seem i am not able to retrieve `UIBarButtonItem._view` of type `UINavigationButton`, which could be used instead of the `customView`, for adding the `badge`, if used from the storyboard directly.
